
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.db_development %>

test:
  <<: *default
  database: <%= Rails.application.credentials.db_test %>

production:
  <<: *default
  database: <%= Rails.application.credentials.db_production %>
