
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD']%>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_DEVELOPMENT']%>

test:
  <<: *default
  database: <%= ENV['DB_TEST']%>

production:
  <<: *default
  database: <%= ENV['DB_PRODUCTION']%>
